
 # 08/15/2021 10:08 am - SSN
 # Replace psdockerrun/products-db with samniyazi/ps-330-products-db-test-20210815

version: "3.7"

services:

  products-db:
    image: samniyazi/ps-330-products-db-test-20210815
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=wired
    networks:
      - ps-330-m03-web-net

  products-api:
    image: psdockerrun/products-api
    ports:
      - "8081:80"
    networks:
      - ps-330-m03-web-net
    depends_on:
      - products-db

  stock-api:
    image: psdockerrun/stock-api
    ports:
      - "8082:8080"
    networks:
      - ps-330-m03-web-net
    depends_on:
      - products-db
  
  web:
    image: psdockerrun/web
    ports:
      - "8080:80"
    networks:
      - ps-330-m03-web-net
    depends_on:
      - products-api      
      - stock-api

networks:
  ps-330-m03-web-net: